### ISSUE TITLE
Why I rerun the code but my accuracy on MNIST just reach 99.1% ?

### ISSUE THREAD

**Issue by Johnwangbin** [P2333/Adaptive-Diversity-Promoting#1]
But in paper the error rate is just 0.28, which means I should get 99.7%.

**Comment by Johnwangbin** [comment]
Sorry to bother you, but this question have troubled me for days.

**Comment by P2333** [comment]
You can update the train_minist.py and try again. 

We have fixed the lr_schedule function, where the original one does not work for MNIST.

**Comment by Johnwangbin** [comment]
Ok, I'll try it. Thanks a lot.
