### ISSUE TITLE
t-sne visulization

### ISSUE THREAD

**Issue by lukk47** [P2333/Adaptive-Diversity-Promoting#6]
Hi, may I know the arguments for the t-sne fucntion(perplexity,early_exaggeration,learning_rate, n_iter, init, ...)  for Figure.2 in the paper? 
I tried quite a few setups, but none of them gave out nice clustering.
Thank you!

**Comment by P2333** [comment]
I used the [tsne function](https://github.com/P2333/Adaptive-Diversity-Promoting/blob/master/tsne.m) in Matlab, with no_dims=2, initial_dims=9, perplexity=30.

**Comment by lukk47** [comment]
Thanks for the details.
